import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Read the terms and conditions for using PhoneAI recommendations.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen py-24 px-4 bg-[#0A0A1A]">
      <div className="max-w-3xl mx-auto text-[#8B8BA7]">
        <h1 className="font-outfit text-4xl font-bold text-white mb-8">Terms of Service</h1>
        
        <p className="mb-6">Last Updated: May 12, 2026</p>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold text-white mb-4">1. Use of Service</h2>
          <p>PhoneAI is an AI-powered recommendation tool. By using this site, you agree that the recommendations are for informational purposes only.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-white mb-4">2. Accuracy of Information</h2>
          <p>While we strive for accuracy, PhoneAI does not guarantee the availability, price, or specifications of any mobile device mentioned. Prices are estimates generated by AI.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-white mb-4">3. Affiliate Disclosure</h2>
          <p>We may earn a small commission if you purchase a product through our links at no extra cost to you.</p>
        </section>

        <Link href="/" className="text-[#6C47FF] hover:underline font-semibold flex items-center gap-2 mt-12">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
