import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Price Disclaimer',
  description: 'Important information about AI-generated price estimates and retailer verification.',
};

export default function PriceDisclaimer() {
  return (
    <div className="min-h-screen py-24 px-4 bg-[#0A0A1A]">
      <div className="max-w-3xl mx-auto text-[#8B8BA7]">
        <h1 className="font-outfit text-4xl font-bold text-white mb-8">Price Disclaimer</h1>
        
        <p className="mb-6">Last Updated: May 12, 2026</p>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold text-white mb-4">AI-Generated Estimates</h2>
          <p>All prices shown on PhoneAI are **estimates** generated by our AI model based on recent market trends. They are NOT live prices pulled directly from retailer databases at the second of viewing.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-white mb-4">Verification Required</h2>
          <p>Prices change frequently on Amazon, Flipkart, and in offline markets. You MUST click the provided retailer links to verify the actual current price before making any purchase decision.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-white mb-4">Offline Pricing</h2>
          <p>Offline prices are "Target Prices" representing a good deal you can negotiate for at a local store. Actual prices may vary by city and shop.</p>
        </section>

        <Link href="/" className="text-[#6C47FF] hover:underline font-semibold flex items-center gap-2 mt-12">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
